### Algoritimos de classificação

base de dados: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

Data de início: 28/03/2021 <br>
Autor: Douglas  <br>

Objetivo: Realizar analise exploratoria dos dados da base de filmes e tentar criar um modelo de classificação;
<br>

Vamos testar duas abordagem: predição da categoria do filme baseado nas variaveis independentes e depois baseado unicamente na descrião

Content
Data:-

Poster_Link - Link of the poster that imdb using <br>
Series_Title = Name of the movie <br>
Released_Year - Year at which that movie released <br>
Certificate - Certificate earned by that movie <br>
Runtime - Total runtime of the movie <br>
Genre - Genre of the movie <br>
IMDB_Rating - Rating of the movie at IMDB site <br>
Overview - mini story/ summary <br>
Meta_score - Score earned by the movie <br>
Director - Name of the Director <br>
Star1,Star2,Star3,Star4 - Name of the Stars <br>
Noofvotes - Total number of votes <br>
Gross - Money earned by that movie <br>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
path = '../Projects/Datasets/imdb_top_1000.csv'

In [3]:
df = pd.read_csv('../Projects/Datasets/imdb_top_1000.csv')

In [4]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [5]:
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
6,https://m.media-amazon.com/images/M/MV5BNGNhMD...,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762"
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
9,https://m.media-amazon.com/images/M/MV5BMmEzNT...,Fight Club,1999,A,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"37,030,102"
10,https://m.media-amazon.com/images/M/MV5BN2EyZj...,The Lord of the Rings: The Fellowship of the Ring,2001,U,178 min,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compani...,92.0,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1661481,"315,544,750"
11,https://m.media-amazon.com/images/M/MV5BNWIwOD...,Forrest Gump,1994,UA,142 min,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",82.0,Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,1809221,"330,252,182"
12,https://m.media-amazon.com/images/M/MV5BOTQ5ND...,"Il buono, il brutto, il cattivo",1966,A,161 min,Western,8.8,A bounty hunting scam joins two men in an unea...,90.0,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,688390,"6,100,000"
13,https://m.media-amazon.com/images/M/MV5BZGMxZT...,The Lord of the Rings: The Two Towers,2002,UA,179 min,"Action, Adventure, Drama",8.7,While Frodo and Sam edge closer to Mordor with...,87.0,Peter Jackson,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,1485555,"342,551,365"
14,https://m.media-amazon.com/images/M/MV5BNzQzOT...,The Matrix,1999,A,136 min,"Action, Sci-Fi",8.7,When a beautiful stranger leads computer hacke...,73.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,1676426,"171,479,930"
15,https://m.media-amazon.com/images/M/MV5BY2NkZj...,Goodfellas,1990,A,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,"46,836,394"
16,https://m.media-amazon.com/images/M/MV5BYmU1ND...,Star Wars: Episode V - The Empire Strikes Back,1980,UA,124 min,"Action, Adventure, Fantasy",8.7,After the Rebels are brutally overpowered by t...,82.0,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1159315,"290,475,067"
17,https://m.media-amazon.com/images/M/MV5BZjA0OW...,One Flew Over the Cuckoo's Nest,1975,A,133 min,Drama,8.7,A criminal pleads insanity and is admitted to ...,83.0,Milos Forman,Jack Nicholson,Louise Fletcher,Michael Berryman,Peter Brocco,918088,"112,000,000"
18,https://m.media-amazon.com/images/M/MV5BNjViNW...,Hamilton,2020,PG-13,160 min,"Biography, Drama, History",8.6,The real life of one of America's foremost fou...,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
19,https://m.media-amazon.com/images/M/MV5BYWZjMj...,Gisaengchung,2019,A,132 min,"Comedy, Drama, Thriller",8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,"53,367,844"
20,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,Soorarai Pottru,2020,U,153 min,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
21,https://m.media-amazon.com/images/M/MV5BZjdkOT...,Interstellar,2014,UA,169 min,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,74.0,Christopher Nolan,Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,1512360,"188,020,017"
22,https://m.media-amazon.com/images/M/MV5BOTMwYj...,Cidade de Deus,2002,A,130 min,"Crime, Drama",8.6,"In the slums of Rio, two kids' paths diverge a...",79.0,Fernando Meirelles,Kátia Lund,Alexandre Rodrigues,Leandro Firmino,Matheus Nachtergaele,699256,"7,563,397"
23,https://m.media-amazon.com/images/M/MV5BMjlmZm...,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
24,https://m.media-amazon.com/images/M/MV5BZjhkMD...,Saving Private Ryan,1998,R,169 min,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",91.0,Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,1235804,"216,540,909"
25,https://m.media-amazon.com/images/M/MV5BMTUxMz...,The Green Mile,1999,A,189 min,"Crime, Drama, Fantasy",8.6,The lives of guards on Death Row are affected ...,61.0,Frank Darabont,Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt,1147794,"136,801,374"
26,https://m.media-amazon.com/images/M/MV5BYmJmM2...,La vita è bella,1997,U,116 min,"Comedy, Drama, Romance",8.6,When an open-minded Jewish librarian and his s...,59.0,Roberto Benigni,Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,623629,"57,598,247"
27,https://m.media-amazon.com/images/M/MV5BOTUwOD...,Se7en,1995,A,127 min,"Crime, Drama, Mystery",8.6,"Two detectives, a rookie and a veteran, hunt a...",65.0,David Fincher,Morgan Freeman,Brad Pitt,Kevin Spacey,Andrew Kevin Walker,1445096,"100,125,643"
28,https://m.media-amazon.com/images/M/MV5BNjNhZT...,The Silence of the Lambs,1991,A,118 min,"Crime, Drama, Thriller",8.6,A young F.B.I. cadet must receive the help of ...,85.0,Jonathan Demme,Jodie Foster,Anthony Hopkins,Lawrence A. Bonney,Kasi Lemmons,1270197,"130,742,922"
29,https://m.media-amazon.com/images/M/MV5BNzVlY2...,Star Wars,1977,UA,121 min,"Action, Adventure, Fantasy",8.6,Luke Skywalker joins forces with a Jedi Knight...,90.0,George Lucas,Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,1231473,"322,740,140"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,https://m.media-amazon.com/images/M/MV5BMTQxND...,My Cousin Vinny,1992,UA,120 min,"Comedy, Crime",7.6,Two New Yorkers accused of murder in rural Ala...,68.0,Jonathan Lynn,Joe Pesci,Marisa Tomei,Ralph Macchio,Mitchell Whitfield,107325,"52,929,168"
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,"453,243"
972,https://m.media-amazon.com/images/M/MV5BNjg5ZD...,Delicatessen,1991,R,99 min,"Comedy, Crime",7.6,Post-apocalyptic surrealist black comedy about...,66.0,Marc Caro,Jean-Pierre Jeunet,Marie-Laure Dougnac,Dominique Pinon,Pascal Benezech,80487,"1,794,187"
973,https://m.media-amazon.com/images/M/MV5BMzFkM2...,Home Alone,1990,U,103 min,"Comedy, Family",7.6,An eight-year-old troublemaker must protect hi...,63.0,Chris Columbus,Macaulay Culkin,Joe Pesci,Daniel Stern,John Heard,488817,"285,761,243"
974,https://m.media-amazon.com/images/M/MV5BNWFlYW...,The Godfather: Part III,1990,A,162 min,"Crime, Drama",7.6,"Follows Michael Corleone, now in his 60s, as h...",60.0,Francis Ford Coppola,Al Pacino,Diane Keaton,Andy Garcia,Talia Shire,359809,"66,666,062"
975,https://m.media-amazon.com/images/M/MV5BMjE0OD...,When Harry Met Sally...,1989,UA,95 min,"Comedy, Drama, Romance",7.6,Harry and Sally have known each other for year...,76.0,Rob Reiner,Billy Crystal,Meg Ryan,Carrie Fisher,Bruno Kirby,195663,"92,823,600"
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,"111,543,479"
977,https://m.media-amazon.com/images/M/MV5BODk1ZW...,The Naked Gun: From the Files of Police Squad!,1988,U,85 min,"Comedy, Crime",7.6,Incompetent police Detective Frank Drebin must...,76.0,David Zucker,Leslie Nielsen,Priscilla Presley,O.J. Simpson,Ricardo Montalban,152871,"78,756,177"
978,https://m.media-amazon.com/images/M/MV5BM2I1ZW...,"Planes, Trains & Automobiles",1987,U,93 min,"Comedy, Drama",7.6,A man must struggle to travel home for Thanksg...,72.0,John Hughes,Steve Martin,John Candy,Laila Robins,Michael McKean,124773,"49,530,280"
979,https://m.media-amazon.com/images/M/MV5BZTllNW...,Lethal Weapon,1987,A,109 min,"Action, Crime, Thriller",7.6,Two newly paired cops who are complete opposit...,68.0,Richard Donner,Mel Gibson,Danny Glover,Gary Busey,Mitchell Ryan,236894,"65,207,127"
980,https://m.media-amazon.com/images/M/MV5BZmI5Yz...,Blood Simple,1984,A,99 min,"Crime, Drama, Thriller",7.6,The owner of a seedy small-town Texas bar disc...,82.0,Joel Coen,Ethan Coen,John Getz,Frances McDormand,Dan Hedaya,87745,"2,150,000"
981,https://m.media-amazon.com/images/M/MV5BNWQ4MG...,On Golden Pond,1981,UA,109 min,Drama,7.6,Norman is a curmudgeon with an estranged relat...,68.0,Mark Rydell,Katharine Hepburn,Henry Fonda,Jane Fonda,Doug McKeon,27650,"119,285,432"
982,https://m.media-amazon.com/images/M/MV5BN2VlNj...,Mad Max 2,1981,A,96 min,"Action, Adventure, Sci-Fi",7.6,"In the post-apocalyptic Australian wasteland, ...",77.0,George Miller,Mel Gibson,Bruce Spence,Michael Preston,Max Phipps,166588,"12,465,371"
983,https://m.media-amazon.com/images/M/MV5BYTU2MW...,The Warriors,1979,UA,92 min,"Action, Crime, Thriller",7.6,"In the near future, a charismatic leader summo...",65.0,Walter Hill,Michael Beck,James Remar,Dorsey Wright,Brian Tyler,93878,"22,490,039"
984,https://m.media-amazon.com/images/M/MV5BMGQ0OG...,The Muppet Movie,1979,U,95 min,"Adventure, Comedy, Family",7.6,Kermit and his newfound friends trek across Am...,74.0,James Frawley,Jim Henson,Frank Oz,Jerry Nelson,Richard Hunt,32802,"76,657,000"
985,https://m.media-amazon.com/images/M/MV5BNDQ3Mz...,Escape from Alcatraz,1979,A,112 min,"Action, Biography, Crime",7.6,Alcatraz is the most secure prison of its time...,76.0,Don Siegel,Clint Eastwood,Patrick McGoohan,Roberts Blossom,Jack Thibeau,121731,"43,000,000"
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,U,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
987,https://m.media-amazon.com/images/M/MV5BNDU1Mj...,Midnight Express,1978,A,121 min,"Biography, Crime, Drama",7.6,"Billy Hayes, an American college student, is c...",59.0,Alan Parker,Brad Davis,Irene Miracle,Bo Hopkins,Paolo Bonacelli,73662,"35,000,000"
988,https://m.media-amazon.com/images/M/MV5BMjM1Nj...,Close Encounters of the Third Kind,1977,U,138 min,"Drama, Sci-Fi",7.6,"Roy Neary, an electric lineman, watches how hi...",90.0,Steven Spielberg,Richard Dreyfuss,François Truffaut,Teri Garr,Melinda Dillon,184966,"132,088,635"
989,https://m.media-amazon.com/images/M/MV5BYzZhOD...,The Long Goodbye,1973,A,112 min,"Comedy, Crime, Drama",7.6,Private investigator Philip Marlowe helps a fr...,87.0,Robert Altman,Elliott Gould,Nina van Pallandt,Sterling Hayden,Mark Rydell,26337,"959,000"
990,https://m.media-amazon.com/images/M/MV5BYjRmY2...,Giù la testa,1971,PG,157 min,"Drama, War, Western",7.6,A low-life bandit and an I.R.A. explosives exp...,77.0,Sergio Leone,Rod Steiger,James Coburn,Romolo Valli,Maria Monti,30144,"696,690"
991,https://m.media-amazon.com/images/M/MV5BMzAyND...,Kelly's Heroes,1970,GP,144 min,"Adventure, Comedy, War",7.6,A group of U.S. soldiers sneaks across enemy l...,50.0,Brian G. Hutton,Clint Eastwood,Telly Savalas,Don Rickles,Carroll O'Connor,45338,"1,378,435"
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612"
993,https://m.media-amazon.com/images/M/MV5BYTE4YW...,Blowup,1966,A,111 min,"Drama, Mystery, Thriller",7.6,A fashion photographer unknowingly captures a ...,82.0,Michelangelo Antonioni,David Hemmings,Vanessa Redgrave,Sarah Miles,John Castle,56513,NaN
994,https://m.media-amazon.com/images/M/MV5BZjQyMG...,A Hard Day's Night,1964,U,87 min,"Comedy, Music, Musical",7.6,"Over two ""typical"" days in the life of The Bea...",96.0,Richard Lester,John Lennon,Paul McCartney,George Harrison,Ringo Starr,40351,"13,780,024"
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

### Ajuste da variavel resposta - <br>
Lets start do know our data. First we're going to exam the Genere and think about our respose variable.

In [6]:
df.groupby('Genre').mean()

                              IMDB_Rating  Meta_score    No_of_Votes
Genre
Action, Adventure                8.180000   71.800000  925533.400000
Action, Adventure, Biography     7.900000         NaN   52397.000000
Action, Adventure, Comedy        7.910000   66.857143  456076.600000
Action, Adventure, Crime         7.600000         NaN   63882.000000
Action, Adventure, Drama         8.150000   80.461538  663989.928571
Action, Adventure, Family        7.600000   78.000000  474827.000000
Action, Adventure, Fantasy       8.200000   78.333333  954767.666667
Action, Adventure, History       7.900000   85.000000  173999.000000
Action, Adventure, Horror        7.900000   71.000000  111512.000000
Action, Adventure, Mystery       7.600000   57.000000  583158.000000
Action, Adventure, Romance       7.900000   97.000000   47175.000000
Action, Adventure, Sci-Fi        7.928571   71.523810  696942.761905
Action, Adventure, Thriller      7.740000   78.400000  408529.800000
Action, Adventure, War           7.700000   68.000000   59548.000000
Action, Adventure, Western       7.800000   85.500000   82560.000000
Action, Biography, Crime         7.866667   81.000000   85794.333333
Action, Biography, Drama         7.942857   67.666667  192873.000000
Action, Comedy, Crime            8.016667   68.000000  244859.166667
Action, Comedy, Fantasy          7.766667   73.666667  210340.666667
Action, Comedy, Mystery          7.800000   81.000000  463466.000000
Action, Comedy, Romance          8.200000         NaN   45642.500000
Action, Crime, Comedy            8.000000         NaN   27721.000000
Action, Crime, Drama             7.880000   73.434783  284026.566667
Action, Crime, Mystery           7.600000   80.000000  508417.000000
Action, Crime, Thriller          7.800000   69.125000  168416.800000
Action, Drama                    7.940000   53.500000  269585.000000
Action, Drama, History           7.766667   77.000000  240970.000000
Action, Drama, Mystery           8.080000   72.000000  373034.600000
Action, Drama, Sci-Fi            8.150000   69.500000  840316.500000
Action, Drama, Sport             8.200000   71.000000  435950.000000
...                                   ...         ...            ...
Drama, Romance                   7.935135   82.687500  244279.891892
Drama, Romance, Sci-Fi           8.150000   89.500000  726218.000000
Drama, Romance, Thriller         7.850000   78.000000  159971.500000
Drama, Romance, War              8.025000   86.750000  173157.250000
Drama, Sci-Fi                    7.933333   88.250000  219994.333333
Drama, Sci-Fi, Thriller          7.700000   67.000000  493902.500000
Drama, Sport                     7.900000   74.666667  299882.833333
Drama, Thriller                  7.857143   75.727273  184477.428571
Drama, Thriller, War             8.100000   74.500000  185847.666667
Drama, Thriller, Western         7.900000   89.000000   97222.000000
Drama, War                       8.073333   82.923077  224782.466667
Drama, War, Western              7.600000   77.000000   30144.000000
Drama, Western                   7.980000   84.800000  429668.200000
Family, Fantasy, Musical         7.800000   67.000000  178731.000000
Family, Sci-Fi                   7.800000   91.000000  372490.000000
Fantasy, Horror                  7.900000         NaN   88794.000000
Fantasy, Horror, Mystery         8.100000         NaN   57428.000000
Film-Noir, Mystery               8.000000   96.000000  148928.000000
Film-Noir, Mystery, Thriller     8.100000   97.000000  158731.000000
Film-Noir, Thriller              7.800000   94.000000   59556.000000
Horror                           7.900000   84.500000  194700.000000
Horror, Mystery, Sci-Fi          8.100000   57.000000  371271.000000
Horror, Mystery, Thriller        7.850000   75.500000  453433.250000
Horror, Sci-Fi                   8.050000   88.000000  409244.500000
Horror, Thriller                 7.800000   88.000000  174831.500000
Mystery, Romance, Thriller       8.300000  100.000000  364368.000000
Mystery, Sci-Fi, Thriller        7.800000   70.000000  383185.000000
Mystery, Thriller                7.977778   78.600000  341362.888889
Thriller                         7.800000   81.000000   27733.000000
Western                          8.350000   78.250000  322416.250000

[202 rows x 3 columns]

How we see, there are movies with more than 1 Genere, so, lets create 3 generes columns

In [7]:
df[['Genre_1','Genre_2', 'Genre_3']] = df['Genre'].str.split(',',expand=True)

In [8]:
df['Genre_1'] = df['Genre_1'].str.replace(' ', '')
df['Genre_2'] = df['Genre_2'].str.replace(' ', '')
df['Genre_3'] = df['Genre_3'].str.replace(' ', '')

We have a problem here. Once that the genre is sort by alphabetic order some genre arent representative in the colum genre_1. Ex Thriller.We have 99 thriller classification in genre_3, but 1 classification in genre_1.

So my first abordage is duplicate the films with one or more genre. But lets see how this comporte:

In [9]:
total = df[['Genre_1', 'Genre_2', 'Genre_3']].isnull().sum()
print('Tamanho da nossa base:', len(df))
total

Tamanho da nossa base: 1000

Genre_1      0
Genre_2    105
Genre_3    354
dtype: int64

Grande parte da nossa base possui mais que 1 genero - (apenas 105 filmes nao possuem 2 generos e 354 nao possuem 3).

In [10]:
df_gen2 = df[df['Genre_2'].notna()]
df_gen3 = df[df['Genre_3'].notna()]
df_gen2['Genre_all'] = df_gen2['Genre_2']
df_gen3['Genre_all'] = df_gen2['Genre_3']
df['Genre_all'] = df['Genre_1']

C:\Users\dougg\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\dougg\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [11]:
df_all_movies = pd.concat([df, df_gen2, df_gen3])

In [12]:
len(df_all_movies)

2541

In [13]:
df_all_movies.groupby('Genre_all').count()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Genre_1,Genre_2,Genre_3
Genre_all,,,,,,,,,,,,,,,,,,,
Action,189,189,189,175,189,189,189,189,156,189,189,189,189,189,189,156,189,189,173
Adventure,196,196,196,189,196,196,196,196,180,196,196,196,196,196,196,170,196,196,182
Animation,82,82,82,80,82,82,82,82,75,82,82,82,82,82,82,67,82,82,81
Biography,109,109,109,107,109,109,109,109,97,109,109,109,109,109,109,96,109,109,97
Comedy,233,233,233,212,233,233,233,233,188,233,233,233,233,233,233,191,233,220,164
Crime,209,209,209,184,209,209,209,209,169,209,209,209,209,209,209,171,209,209,174
Drama,724,724,724,644,724,724,724,724,600,724,724,724,724,724,724,597,724,639,448
Family,56,56,56,53,56,56,56,56,50,56,56,56,56,56,56,48,56,56,50
Fantasy,66,66,66,61,66,66,66,66,58,66,66,66,66,66,66,56,66,66,62
Film-Noir,19,19,19,15,19,19,19,19,11,19,19,19,19,19,19,11,19,19,13
History,56,56,56,53,56,56,56,56,48,56,56,56,56,56,56,43,56,56,53
Horror,32,32,32,23,32,32,32,32,27,32,32,32,32,32,32,22,32,30,19
Music,35,35,35,33,35,35,35,35,29,35,35,35,35,35,35,33,35,35,28
Musical,17,17,17,16,17,17,17,17,12,17,17,17,17,17,17,14,17,17,16
Mystery,99,99,99,87,99,99,99,99,80,99,99,99,99,99,99,84,99,99,85
Romance,125,125,125,114,125,125,125,125,104,125,125,125,125,125,125,107,125,125,81
Sci-Fi,67,67,67,64,67,67,67,67,62,67,67,67,67,67,67,61,67,67,52
Sport,19,19,19,19,19,19,19,19,17,19,19,19,19,19,19,19,19,19,13
Thriller,137,137,137,117,137,137,137,137,118,137,137,137,137,137,137,110,137,136,103
War,51,51,51,41,51,51,51,51,45,51,51,51,51,51,51,37,51,51,34
Western,20,20,20,19,20,20,20,20,20,20,20,20,20,20,20,16,20,16,10

### Variable Star -> Dummy

In [14]:
#Tratando variaveis:
#criar um arry com todas as estrelas:

df_all_movies['all_stars'] = df_all_movies['Star1'].str.replace(' ', '') + df_all_movies['Star2'].str.replace(' ', '') + df_all_movies['Star3'].str.replace(' ', '') + df_all_movies['Star4'].str.replace(' ', '')

In [15]:
df_all_movies['all_stars'].head()

0       TimRobbinsMorganFreemanBobGuntonWilliamSadler
1            MarlonBrandoAlPacinoJamesCaanDianeKeaton
2    ChristianBaleHeathLedgerAaronEckhartMichaelCaine
3         AlPacinoRobertDeNiroRobertDuvallDianeKeaton
4          HenryFondaLeeJ.CobbMartinBalsamJohnFiedler
Name: all_stars, dtype: object

In [16]:
df_all_movies['all_stars2'] = df_all_movies[['Star1', 'Star2','Star3','Star4']].agg(','.join, axis=1)

In [17]:
df_all_movies['all_stars2'] = df_all_movies['all_stars2'].str.replace(' ', '')

In [18]:
df_all_movies['all_stars2'].head()

0     TimRobbins,MorganFreeman,BobGunton,WilliamSadler
1          MarlonBrando,AlPacino,JamesCaan,DianeKeaton
2    ChristianBale,HeathLedger,AaronEckhart,Michael...
3       AlPacino,RobertDeNiro,RobertDuvall,DianeKeaton
4        HenryFonda,LeeJ.Cobb,MartinBalsam,JohnFiedler
Name: all_stars2, dtype: object

In [19]:
import ast

In [20]:
df_all_movies.all_stars2.apply(lambda x: x[0:-1].split(','))

0      [TimRobbins, MorganFreeman, BobGunton, William...
1        [MarlonBrando, AlPacino, JamesCaan, DianeKeato]
2      [ChristianBale, HeathLedger, AaronEckhart, Mic...
3      [AlPacino, RobertDeNiro, RobertDuvall, DianeKe...
4      [HenryFonda, LeeJ.Cobb, MartinBalsam, JohnFiedle]
5      [ElijahWood, ViggoMortensen, IanMcKellen, Orla...
6      [JohnTravolta, UmaThurman, SamuelL.Jackson, Br...
7      [LiamNeeson, RalphFiennes, BenKingsley, Caroli...
8      [LeonardoDiCaprio, JosephGordon-Levitt, Elliot...
9         [BradPitt, EdwardNorton, MeatLoaf, ZachGrenie]
10      [ElijahWood, IanMcKellen, OrlandoBloom, SeanBea]
11        [TomHanks, RobinWright, GarySinise, SallyFiel]
12     [ClintEastwood, EliWallach, LeeVanCleef, AldoG...
13     [ElijahWood, IanMcKellen, ViggoMortensen, Orla...
14     [LillyWachowski, KeanuReeves, LaurenceFishburn...
15     [RobertDeNiro, RayLiotta, JoePesci, LorraineBr...
16     [MarkHamill, HarrisonFord, CarrieFisher, Billy...
17     [JackNicholson, LouiseFletcher, MichaelBerryma...
18     [Lin-ManuelMiranda, PhillipaSoo, LeslieOdomJr....
19     [Kang-hoSong, LeeSun-kyun, ChoYeo-jeong, ChoiW...
20      [Suriya, Madhavan, PareshRawal, AparnaBalamural]
21     [MatthewMcConaughey, AnneHathaway, JessicaChas...
22     [KátiaLund, AlexandreRodrigues, LeandroFirmino...
23     [DaveighChase, SuzannePleshette, MiyuIrino, Ru...
24        [TomHanks, MattDamon, TomSizemore, EdwardBurn]
25     [TomHanks, MichaelClarkeDuncan, DavidMorse, Bo...
26     [RobertoBenigni, NicolettaBraschi, GiorgioCant...
27     [MorganFreeman, BradPitt, KevinSpacey, AndrewK...
28     [JodieFoster, AnthonyHopkins, LawrenceA.Bonney...
29     [MarkHamill, HarrisonFord, CarrieFisher, AlecG...
                             ...
956          [BarryCook, Ming-NaWen, EddieMurphy, BDWon]
957    [JohnnyDepp, BenicioDelToro, TobeyMaguire, Mic...
958    [SusanneLothar, UlrichMühe, ArnoFrisch, FrankG...
959    [RufusSewell, KieferSutherland, JenniferConnel...
960     [RobertDeNiro, KevinBacon, BradPitt, JasonPatri]
963    [BruceWillis, JeremyIrons, SamuelL.Jackson, Gr...
964    [JohnnyDepp, GaryFarmer, CrispinGlover, LanceH...
966        [TomHanks, BillPaxton, KevinBacon, GarySinis]
967    [ZbigniewZamachowski, JulieDelpy, JanuszGajos,...
968    [MichaelDouglas, RobertDuvall, BarbaraHershey,...
971    [MikiImai, ToshirôYanagiba, YokoHonna, MayumiI...
975     [BillyCrystal, MegRyan, CarrieFisher, BrunoKirb]
976    [JohnMusker, JodiBenson, SamuelE.Wright, ReneA...
979     [MelGibson, DannyGlover, GaryBusey, MitchellRya]
980    [EthanCoen, JohnGetz, FrancesMcDormand, DanHeday]
982    [MelGibson, BruceSpence, MichaelPreston, MaxPh...
983    [MichaelBeck, JamesRemar, DorseyWright, BrianT...
984        [JimHenson, FrankOz, JerryNelson, RichardHun]
985    [ClintEastwood, PatrickMcGoohan, RobertsBlosso...
986    [JohnHubley, JohnHurt, RichardBriers, RalphRic...
987    [BradDavis, IreneMiracle, BoHopkins, PaoloBona...
989    [ElliottGould, NinavanPallandt, SterlingHayden...
990    [RodSteiger, JamesCoburn, RomoloValli, MariaMont]
991    [ClintEastwood, TellySavalas, DonRickles, Carr...
992    [PhilHarris, SebastianCabot, LouisPrima, Bruce...
993    [DavidHemmings, VanessaRedgrave, SarahMiles, J...
994    [JohnLennon, PaulMcCartney, GeorgeHarrison, Ri...
995    [AudreyHepburn, GeorgePeppard, PatriciaNeal, B...
997    [BurtLancaster, MontgomeryClift, DeborahKerr, ...
999    [RobertDonat, MadeleineCarroll, LucieMannheim,...
Name: all_stars2, Length: 2541, dtype: object

In [21]:
df_all_movies['all_stars2'].head()

0     TimRobbins,MorganFreeman,BobGunton,WilliamSadler
1          MarlonBrando,AlPacino,JamesCaan,DianeKeaton
2    ChristianBale,HeathLedger,AaronEckhart,Michael...
3       AlPacino,RobertDeNiro,RobertDuvall,DianeKeaton
4        HenryFonda,LeeJ.Cobb,MartinBalsam,JohnFiedler
Name: all_stars2, dtype: object

In [22]:
df_all_movies['all_stars2'] = df_all_movies.all_stars2.apply(lambda x: x[0:-1].split(',')).apply(lambda x:['star_' + y for y in x if y])

Hello everyone. I'm work in a classification projecto of movies genere (using the imd-dataset: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows). 
I created a column with all stars that be in the movie from the columns Star1, Star2, Star3, Star4 and now I wanna use the get_dummy to have dummies colums about every star (ex. col_star_TimRobbins, col_star_MorganFreeman...).

But

In [23]:
df_all_movies['all_stars2'].head()

0    [star_TimRobbins, star_MorganFreeman, star_Bob...
1    [star_MarlonBrando, star_AlPacino, star_JamesC...
2    [star_ChristianBale, star_HeathLedger, star_Aa...
3    [star_AlPacino, star_RobertDeNiro, star_Robert...
4    [star_HenryFonda, star_LeeJ.Cobb, star_MartinB...
Name: all_stars2, dtype: object

In [24]:
(df_all_movies['all_stars2'].apply(pd.Series))

,0,1,2,3
0,star_TimRobbins,star_MorganFreeman,star_BobGunton,star_WilliamSadle
1,star_MarlonBrando,star_AlPacino,star_JamesCaan,star_DianeKeato
2,star_ChristianBale,star_HeathLedger,star_AaronEckhart,star_MichaelCain
3,star_AlPacino,star_RobertDeNiro,star_RobertDuvall,star_DianeKeato
4,star_HenryFonda,star_LeeJ.Cobb,star_MartinBalsam,star_JohnFiedle
5,star_ElijahWood,star_ViggoMortensen,star_IanMcKellen,star_OrlandoBloo
6,star_JohnTravolta,star_UmaThurman,star_SamuelL.Jackson,star_BruceWilli
7,star_LiamNeeson,star_RalphFiennes,star_BenKingsley,star_CarolineGoodal
8,star_LeonardoDiCaprio,star_JosephGordon-Levitt,star_ElliotPage,star_KenWatanab
9,star_BradPitt,star_EdwardNorton,star_MeatLoaf,star_ZachGrenie
10,star_ElijahWood,star_IanMcKellen,star_OrlandoBloom,star_SeanBea
11,star_TomHanks,star_RobinWright,star_GarySinise,star_SallyFiel
12,star_ClintEastwood,star_EliWallach,star_LeeVanCleef,star_AldoGiuffr
13,star_ElijahWood,star_IanMcKellen,star_ViggoMortensen,star_OrlandoBloo
14,star_LillyWachowski,star_KeanuReeves,star_LaurenceFishburne,star_Carrie-AnneMos
15,star_RobertDeNiro,star_RayLiotta,star_JoePesci,star_LorraineBracc
16,star_MarkHamill,star_HarrisonFord,star_CarrieFisher,star_BillyDeeWilliam
17,star_JackNicholson,star_LouiseFletcher,star_MichaelBerryman,star_PeterBrocc
18,star_Lin-ManuelMiranda,star_PhillipaSoo,star_LeslieOdomJr.,star_RenéeEliseGoldsberr
19,star_Kang-hoSong,star_LeeSun-kyun,star_ChoYeo-jeong,star_ChoiWoo-si
20,star_Suriya,star_Madhavan,star_PareshRawal,star_AparnaBalamural
21,star_MatthewMcConaughey,star_AnneHathaway,star_JessicaChastain,star_MackenzieFo
22,star_KátiaLund,star_AlexandreRodrigues,star_LeandroFirmino,star_MatheusNachtergael
23,star_DaveighChase,star_SuzannePleshette,star_MiyuIrino,star_RumiHiirag
24,star_TomHanks,star_MattDamon,star_TomSizemore,star_EdwardBurn
25,star_TomHanks,star_MichaelClarkeDuncan,star_DavidMorse,star_BonnieHun
26,star_RobertoBenigni,star_NicolettaBraschi,star_GiorgioCantarini,star_GiustinoDuran
27,star_MorganFreeman,star_BradPitt,star_KevinSpacey,star_AndrewKevinWalke
28,star_JodieFoster,star_AnthonyHopkins,star_LawrenceA.Bonney,star_KasiLemmon
29,star_MarkHamill,star_HarrisonFord,star_CarrieFisher,star_AlecGuinnes
...,...,...,...,...
956,star_BarryCook,star_Ming-NaWen,star_EddieMurphy,star_BDWon
957,star_JohnnyDepp,star_BenicioDelToro,star_TobeyMaguire,star_MichaelLeeGogi
958,star_SusanneLothar,star_UlrichMühe,star_ArnoFrisch,star_FrankGierin
959,star_RufusSewell,star_KieferSutherland,star_JenniferConnelly,star_WilliamHur
960,star_RobertDeNiro,star_KevinBacon,star_BradPitt,star_JasonPatri
963,star_BruceWillis,star_JeremyIrons,star_SamuelL.Jackson,star_GrahamGreen
964,star_JohnnyDepp,star_GaryFarmer,star_CrispinGlover,star_LanceHenrikse
966,star_TomHanks,star_BillPaxton,star_KevinBacon,star_GarySinis
967,star_ZbigniewZamachowski,star_JulieDelpy,star_JanuszGajos,star_JerzyStuh
968,star_MichaelDouglas,star_RobertDuvall,star_BarbaraHershey,star_RachelTicoti
971,star_MikiImai,star_ToshirôYanagiba,star_YokoHonna,star_MayumiIzuk
975,star_BillyCrystal,star_MegRyan,star_CarrieFisher,star_BrunoKirb
976,star_JohnMusker,star_JodiBenson,star_SamuelE.Wright,star_ReneAuberjonoi
979,star_MelGibson,star_DannyGlover,star_GaryBusey,star_MitchellRya
980,star_EthanCoen,star_JohnGetz,star_FrancesMcDormand,star_DanHeday
982,star_MelGibson,star_BruceSpence,star_MichaelPreston,star_MaxPhipp
983,star_MichaelBeck,star_JamesRemar,star_DorseyWright,star_BrianTyle
984,star_JimHenson,star_FrankOz,star_JerryNelson,star_RichardHun
985,star_ClintEastwood,star_PatrickMcGoohan,star_RobertsBlossom,star_JackThibea
986,star_JohnHubley,star_JohnHurt,star_RichardBriers,star_RalphRichardso
987,star_BradDavis,star_IreneMiracle,star_BoHopkins,star_PaoloBonacell
989,star_ElliottGould,star_NinavanPallandt,star_SterlingHayden,star_MarkRydel
990,star_RodSteiger,star_JamesCoburn,star_RomoloValli,star_MariaMont
991,star_ClintEastwood,star_TellySavalas,star_DonRickles,star_CarrollO'Conno
992,star_PhilHarris,star_SebastianCabot,star_LouisPrima,star_BruceReitherma
993,star_DavidHemmings,star_VanessaRedgrave,star_SarahMiles,star_JohnCastl
994,star_JohnLennon,star_PaulMcCartney,star_GeorgeHarrison,star_RingoStar
995,star_AudreyHepburn,star_GeorgePeppard,star_PatriciaNeal,star_BuddyEbse
997,star_BurtLancaster,star_MontgomeryClift,star_DeborahKerr,star_DonnaRee
999,star_RobertDonat,star_MadeleineCarroll,star_LucieMannheim,star_GodfreyTearl

In [25]:
type(df_all_movies)

pandas.core.frame.DataFrame

In [26]:
df_all_star = df_all_movies['all_stars2'].apply(pd.Series)

In [27]:
type(df_all_star)

pandas.core.frame.DataFrame

In [28]:
df_all_star.head()

,0,1,2,3
0,star_TimRobbins,star_MorganFreeman,star_BobGunton,star_WilliamSadle
1,star_MarlonBrando,star_AlPacino,star_JamesCaan,star_DianeKeato
2,star_ChristianBale,star_HeathLedger,star_AaronEckhart,star_MichaelCain
3,star_AlPacino,star_RobertDeNiro,star_RobertDuvall,star_DianeKeato
4,star_HenryFonda,star_LeeJ.Cobb,star_MartinBalsam,star_JohnFiedle

In [29]:
df_all_star_one_collum = DataFrame(df_all_star[0]+','+ df_all_star[1]+',' +df_all_star[2]+','+ df_all_star[3])

NameError: name 'DataFrame' is not defined

In [ ]:
df_all_star_one_collum = DataFrame(pd.concat([df_all_star[0], df_all_star[1],df_all_star[2], df_all_star[3]]))

In [ ]:
type(df_all_star_one_collum)

In [ ]:
from pandas import Series, DataFrame

In [ ]:
type(df_all_star_one_collum)

In [ ]:
df_all_star_one_collum[0].str.value_counts()

We have a lot of 'Stars' with just one movie, so, lets removed this stars

In [ ]:
df_all_star_one_collum[df_all_star_one_collum.value_counts() <8]

In [ ]:
stars_to_remove = df_all_star_one_collum[df_all_star_one_collum.value_counts() <8]

In [ ]:
df = df[df.ids != "aball"]

In [ ]:
series_obj = Series

In [ ]:
stars_to_remove = df_all_star_one_collum.value_counts() <8

In [ ]:
stars_to_remove2 = df_all_star_one_collum[df_all_star_one_collum.value_counts() <8]

In [ ]:
stars_to_remove

In [ ]:
len(stars_to_remove)

In [ ]:
df_all_star_one_collum[df_all_star_one_collum == 'star_RobertDeNiro'].value_counts()

In [ ]:
stars_to_remove

In [ ]:
import re

In [ ]:
df_all_movies['all_star_3'] = df_all_movies['all_star_3'].str.replace('|'.join(map(re.escape, To_remove_lst)), '')

In [ ]:
df['name'] = df['name'].str.replace('|'.join(map(re.escape, To_remove_lst)), '')

In [ ]:
df_all_movies.set_index('Series_Title', drop=False, append=True)

In [ ]:
print(df_all_movies['all_stars2'][3])

In [ ]:
dummie2 = pd.get_dummies(df_all_movies['all_stars2'].apply(pd.Series))

In [ ]:
dummie2

In [ ]:
#dummie = pd.get_dummies(df_all_movies['all_stars2'].apply(pd.Series)).sum(level=0)

In [ ]:
df_all_movies = pd.concat([df_all_movies, dummie2], axis = 1)

In [ ]:
df_all_movies['2_star_BruceWillis']

In [ ]:
with pd.option_context('display.max_columns',None):
    display(df_all_movies.head())

In [ ]:
df_all_movies.head()

In [ ]:
df_all_movies.drop()

so we created mora than 3000 variables, its not sound good

In [ ]:
dummie.head()

In [ ]:
#df_all_movies_2 = pd.get_dummies(df_all_movies['all_stars2'].apply(pd.Series)).sum(level=0)

In [ ]:
df_all_movies_2.head()

In [ ]:
df_all_movies_2

In [ ]:
df_all_movies_2 = df_all_movies.copy()

In [ ]:
df_all_movies_2

In [ ]:
from IPython.display import display

In [ ]:
with pd.option_context('display.max_columns',None):
    display(df_all_movies.head())

In [ ]:
df_all_movies.head()

### EDA

In [ ]:
continuous = [f for f in df_all_movies.columns if df_all_movies.dtypes[f] != 'object']
continuous